# docker-compose.yml
version: '3'

services:
  web-service:
    build: .
    command: gunicorn -b 0.0.0.0:5000 server:app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    volumes:
      - chroma_pdf_data:/app/CHROMA_PDF
volumes:
  chroma_pdf_data: