# docker-compose.yml
version: '3'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:5001 server:app
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: production

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "5000:5000"
    depends_on:
      - web